CREATE TABLE `Items Table` (

    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `category` VARCHAR(100) NOT NULL,
    `description` VARCHAR(255) NOT NULL,
    `part_number` VARCHAR(100) NOT NULL,
    `quantity_on_hand` INT DEFAULT 0,
    `last_updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

);





INSERT INTO `Items Table` (`category`, `description`, `part_number`, `quantity_on_hand`) VALUES

('PPE'         , 'Gloves mig tillman SMALL'                                    , '1540S'               , 0),
('PPE'         , 'Gloves mig tillman MEDIUM'                                   , '1540M'               , 0),
('PPE'         , 'Gloves mig tillman LARGE'                                    , '1540L'               , 0),
('PPE'         , 'Gloves mig tillman EXTRA LARGE'                              , '1540XL'              , 0),
('PPE'         , 'Gloves tig tillman SMALL'                                    , '24cs'                , 0),
('PPE'         , 'Gloves tig tillman MEDIUM'                                   , '24cm'                , 0),
('PPE'         , 'Gloves tig tillman LARGE'                                    , '24cl'                , 0),
('PPE'         , 'Gloves tig tillman EXTRA LARGE'                              , '24cxl'               , 0),
('PPE'         , 'Jacket FR  small'                                            , 'SM-6230S'            , 0),
('PPE'         , 'Jacket FR  medium'                                           , 'MD-6230M'            , 0),
('PPE'         , 'Jacket FR  large'                                            , 'LG-6230L'            , 0),
('PPE'         , 'Jacket FR  extra large'                                      , 'XL-6230XL'           , 0),
('PPE'         , 'Jacket FR  2x large'                                         , 'XL-62302X'           , 0),
('PPE'         , 'Jacket leather girls EXTRA SMALL'                            , 'REVJH1515-NB-XS'     , 0),
('PPE'         , 'Jacket leather jacket SMALL'                                 , 'JL1030BB-S'          , 0),
('PPE'         , 'Jacket leather jacket MEDIUM'                                , 'JL1030BB-M'          , 0),
('PPE'         , 'Jacket leather jacket LARGE'                                 , 'JL1030BB-L'          , 0),
('PPE'         , 'Jacket leather jacket EXTRA LARGE'                           , 'JL1030BB-XL'         , 0),
('PPE'         , 'Jacket leather jacket 2XL'                                   , 'JL1030BB-2X'         , 0),
('PPE'         , 'Jacket leather jacket 3XL'                                   , 'JL1030BB-3X'         , 0),
('PPE'         , '3M Respirator filter'                                        , '2091 P100'           , 0),
('PPE'         , 'Ear plugs 3M'                                                , '1110'                , 0),
                                              
('MIG'         , 'Contact Tip .035'                                            , '403-20-35'           , 1),
('MIG'         , 'Contact Tip .045'                                            , '403-20-45'           , 0),
('MIG'         , 'Diffuser (Tregaskiss)'                                       , '404-26'              , 0),
('MIG'         , 'Felt Wire Lube (Lube Matic)'                                 , '0070660'             , 0),
('MIG'         , 'Miller Briefcase Wire Guide'                                 , '150994'              , 0),
('MIG'         , 'Drive Roller'                                                , '189285'              , 0),
('MIG'         , 'Mig Gun Insulator'                                           , '4532R'               , 0),
('MIG'         , 'Nozzle Short Circuit'                                        , '401-42-50'           , 0),
('MIG'         , 'Nozzle Spray Transfer'                                       , '401-7-62'            , 0),
('MIG'         , 'Nozzle HD Copper'                                            , '401-48-62'           , 0),
('MIG'         , 'Replacement MIG guns'                                        , 'Q3010AR3EMC'         , 0),
('MIG'         , 'Filler MIG .045"'                                            , 'ER70S-6'             , 0),
('MIG'         , 'Filler MIG .035"'                                            , 'ER70S-6'             , 0),
       
('TIG'         , 'CK Torch Insulator (trailing)'                               , ''                    , 0),
('TIG'         , 'Torch (Miller)'                                              , ''                    , 0),
('TIG'         , 'Miller Torch Insulator (leading)'                            , ''                    , 0),
('TIG'         , 'Miller Torch Insulator (trailing)'                           , ''                    , 0),
('TIG'         , 'Gas Lens 1/16'                                               , ''                    , 0),
('TIG'         , 'Gas Lens 3/32'                                               , ''                    , 0),
('TIG'         , 'Gas Lens 1/8'                                                , ''                    , 0),
('TIG'         , 'Cup #4'                                                      , ''                    , 0),
('TIG'         , 'Cup #5'                                                      , ''                    , 0),
('TIG'         , 'Cup #6'                                                      , ''                    , 0),
('TIG'         , 'Cup #7'                                                      , ''                    , 0),
('TIG'         , 'Cup #8'                                                      , ''                    , 0),
('TIG'         , 'Back Cap Small'                                              , ''                    , 0),
('TIG'         , 'Back Cap Medium'                                             , ''                    , 0),
('TIG'         , 'Back Cap Large'                                              , ''                    , 0),
('TIG'         , 'Collet 1/16'                                                 , ''                    , 0),
('TIG'         , 'Collet 3/32'                                                 , ''                    , 0),
('TIG'         , 'Collet 1/8'                                                  , ''                    , 0),
('TIG'         , 'Collet Body 1/16'                                            , ''                    , 0),
('TIG'         , 'Collet Body 3/32'                                            , ''                    , 0),
('TIG'         , 'Collet Body 1/8'                                             , ''                    , 0),
('TIG'         , 'Foot Pedal'                                                  , ''                    , 0),
('TIG'         , '1/16 tungsten ceriated'                                      , 'T1167GC2'            , 0),
('TIG'         , '3/32 tungsten ceriated'                                      , 'T3327GC2'            , 1),
('TIG'         , '1/8 tungsten ceriated'                                       , 'T187GC2'             , 0),
('TIG'         , 'Filler Aluminium .045"'                                      , 'ER4043'              , 0),
('TIG'         , 'Filler Aluminium 1/16"'                                      , 'ER4043'              , 0),
('TIG'         , 'Filler Aluminium 3/32"'                                      , 'ER4043'              , 0),
('TIG'         , 'Filler Aluminium 1/8"'                                       , 'ER4043'              , 0),
('TIG'         , 'Filler Stainless Steel  .045"'                               , '308L'                , 0),
('TIG'         , 'Filler Stainless Steel  1/16"'                               , '308L'                , 0),
('TIG'         , 'Filler Stainless Steel  3/32"'                               , '308L'                , 0),
('TIG'         , 'Filler Stainless Steel  1/8"'                                , '308L'                , 0),
('TIG'         , 'Filler Mild Steel  .035"'                                    , 'ER70S-2'             , 0),
('TIG'         , 'Filler Mild Steel  .045"'                                    , 'ER70S-2'             , 0),
('TIG'         , 'Filler Mild Steel  1/16"'                                    , 'ER70S-2'             , 0),
('TIG'         , 'Filler Mild Steel  3/32"'                                    , 'ER70S-2'             , 0),
('TIG'         , 'Filler Mild Steel  1/8"'                                     , 'ER70S-2'             , 0),

('Stick'       , 'Stinger Replacement'                                         , 'ARC-532'             , 0),
('Stick'       , 'Filler E6010 1/8"'                                           , 'E6010-18'            , 0),
('Stick'       , 'Filler E6010 3/32"'                                          , 'E6010-332'           , 0),
('Stick'       , 'Filler E6011 1/8"'                                           , 'E6011-18'            , 0),
('Stick'       , 'Filler E6013 3/32"'                                          , 'E6013-332'           , 0),
('Stick'       , 'Filler E7018 1/8"'                                           , 'E7018-18'            , 0),
('Stick'       , 'Filler E7018 3/32"'                                          , 'E7018-332'           , 0),
                            
('Oxy-Fuel'    , 'Propane Nozzle 000'                                          , '1501200'             , 0),
('Oxy-Fuel'    , 'Propane Nozzle 00'                                           , '1501210'             , 0),
('Oxy-Fuel'    , 'Propane Nozzle 0'                                            , '1501220'             , 0),
('Oxy-Fuel'    , 'Propane Nozzle 1'                                            , '1501230'             , 0),
('Oxy-Fuel'    , 'Propane Nozzle 2'                                            , '1501240'             , 0),
('Oxy-Fuel'    , 'Acetylene Nozzle 000'                                        , '000-1-101'           , 0),
('Oxy-Fuel'    , 'Acetylene Nozzle 00'                                         , '00-1-101'            , 0),
('Oxy-Fuel'    , 'Acetylene Nozzle 0'                                          , '0-1-101'             , 0),
('Oxy-Fuel'    , 'Acetylene Nozzle 1'                                          , '1-1-101'             , 0),
('Oxy-Fuel'    , 'Acetylene Nozzle 2'                                          , '2-1-101'             , 0),
('Oxy-Fuel'    , 'Acetylene Track Torch 00'                                    , '6290-2/0'            , 0),
('Oxy-Fuel'    , 'Acetylene Track Torch 0'                                     , '6290-1'              , 0),
('Oxy-Fuel'    , 'Acetylene Track Torch 1'                                     , '6290-1'              , 0),
('Oxy-Fuel'    , 'Acetylene Track Torch 2'                                     , '6290-2'              , 0),
('Oxy-Fuel'    , 'Torch Assembly'                                              , '62-5F (1003451)'     , 0),
('Oxy-Fuel'    , 'Spare Hoses'                                                 , '907-T254'            , 0),
('Oxy-Fuel'    , 'Protective Sleeves Tillman'                                  , '582-025'             , 0),
('Oxy-Fuel'    , 'Strikers (Lincoln)'                                          , 'KH572'               , 0),
('Oxy-Fuel'    , 'Flint Replacements'                                          , ''                    , 0),
('Oxy-Fuel'    , 'Torch Tip Cleaners'                                          , ''                    , 0),
('Oxy-Fuel'    , 'Regulator Oxygen'                                            , ''                    , 0),
('Oxy-Fuel'    , 'Regulator Fuel'                                              , ''                    , 0),
('Oxy-Fuel'    , 'Quick Connect Oxygen'                                        , ''                    , 0),
('Oxy-Fuel'    , 'Quick Connect Fuel'                                          , ''                    , 0),
('Oxy-Fuel'    , 'Flashback Arrestor (Oxygen) Fuel Safe Western Enterprises'   , 'FA-30'               , 0),
('Oxy-Fuel'    , 'Flashback Arrestor (Fuel) Fuel Safe Western Enterprises'     , ''                    , 0),
('Oxy-Fuel'    , '2pc Acetylene torches Harris lower'                          , '315FC+'              , 0),
('Oxy-Fuel'    , '2pc Acetylene torches Harris upper'                          , 'CA2460+'             , 0),
('Oxy-Fuel'    , 'Propane Nozzle 000'                                          , '1501200'             , 0),
('Oxy-Fuel'    , 'Filler Bronze 3/32'                                          , '015FC50'             , 0),
('Oxy-Fuel'    , 'Filler Bronze Fluxed 3/32'                                   , 'RBCuZn-C'            , 0),

('Plasma'      , 'Gouge Shield'                                                , 'HT220798'            , 0),
('Plasma'      , 'Gouge Nozzle'                                                , 'HT220797'            , 0),
('Plasma'      , 'Cut Shield'                                                  , 'HT220818'            , 0),
('Plasma'      , 'Cut Nozzle 65A'                                              , 'HT220819'            , 0),
('Plasma'      , 'Retaining Cap'                                               , 'HT220854'            , 0),
('Plasma'      , 'Swirl Ring'                                                  , 'HT220857'            , 0),
('Plasma'      , 'Electrode'                                                   , 'HT220842'            , 0),
     
('Gouging'     , 'Electrode Carbon Arc Round 1/4"'                             , '22043003'            , 0),
('Gouging'     , 'Electrode Carbon Arc Round 3/16"'                            , '2203-3003'           , 0),
('Gouging'     , 'Electrode Carbon Arc Round 3/8"'                             , '22063003'            , 0),
('Gouging'     , 'Electrode Carbon Arc Round 1/2"'                             , '22082003'            , 0),
('Gouging'     , 'Electrode Carbon Arc Flat 1/4"'                              , '2204-3003'           , 0),
('Gouging'     , 'Electrode Carbon Arc Flat 3/8 X 5/32'                        , 'ARC35099003P'        , 0),
('Gouging'     , 'Arc Gouging Torch'                                           , 'AEC3500-1'           , 0),


('Raw-Material', 'Sheet Mild Steel 1/16" x 4\' x 8\' Cold Rolled'              , ''                   ,  1),
('Raw-Material', 'Sheet Mild Steel 1/8" x 4\' x 8\' Cold Rolled'               , ''                   ,  0),
('Raw-Material', 'Sheet Mild Steel 1/16" x 4\' x 8\' Hot Rolled'               , ''                   ,  0),
('Raw-Material', 'Sheet Mild Steel 1/8" x 4\' x 8\' Hot Rolled'                , ''                   ,  2),
('Raw-Material', 'Sheet Mild Steel 1/4" x 4\' x 8\' Hot Rolled'                , ''                   ,  1),
('Raw-Material', 'Sheet Mild Steel 20 gauge x 4\' x 8\' Hot Rolled'            , ''                   ,  1),
('Raw-Material', 'Sheet Stainless 1/16" x 4\' x 8\''                           , ''                   ,  2),
('Raw-Material', 'Sheet Stainless 1/8" x 4\' x 8\''                            , ''                   ,  3),
('Raw-Material', 'Sheet Aluminum  1/16" x 4\' x 8\''                           , ''                   ,  2),
('Raw-Material', 'Sheet Aluminum 1/8" x 4\' x 8\''                             , ''                   ,  4),
('Raw-Material', 'Bar Merchant 1/4" x 6" x 20\''                               , ''                   ,  1),
('Raw-Material', 'Bar Merchant 3/8" x 6" x 20\''                               , ''                   , 12),
('Raw-Material', 'Bar Merchant 1/2" x 6" x 20\''                               , ''                   ,  0),
('Raw-Material', 'Bar Merchant 3/4" x 6" x 20\''                               , ''                   ,  2),

              
('Maintenance' , 'Grinding Wheel'                                              , ''                   ,  0),
('Maintenance' , 'Cutting disc'                                                , ''                   ,  0),
('Maintenance' , 'Wire Wheel Brush'                                            , ''                   ,  0),
('Maintenance' , 'Cup Wire Brush'                                              , ''                   ,  0),
('Maintenance' , 'Flap Discs'                                                  , ''                   ,  0),
('Maintenance' , 'Pirranah Diamond Wheel Replacement'                          , ''                   ,  0),
('Maintenance' , 'Belt Sander Replacement Belt'                                , ''                   ,  0),
('Maintenance' , 'Stainless Steel Bristles'                                    , ''                   ,  0),
('Maintenance' , 'Mild Steel Bristles'                                         , ''                   ,  0),
('Maintenance' , 'Brass Bristles'                                              , ''                   ,  0),
('Maintenance' , 'Dead-blow Hammer'                                            , ''                   ,  0),
('Maintenance' , 'Baby Hammer'                                                 , ''                   ,  0),
('Maintenance' , 'Big Boy Hammer'                                              , ''                   ,  0),
('Maintenance' , 'Blade Big Kalamazoo Fine'                                    , ''                   ,  0),
('Maintenance' , 'Blade Big Kalamazoo Coarse'                                  , ''                   ,  0),
('Maintenance' , 'Blade Baby Kalamazoo Fine'                                   , ''                   ,  0),
('Maintenance' , 'Blade Baby Kalamazoo Coarse'                                 , ''                   ,  0),
('Maintenance' , 'Cooling Fan (Nu tone)'                                       , ''                   ,  0),
('Maintenance' , 'Power Switch Miller Wire Feed '                              , '29FG26'             ,  0),

('Gas'         , 'Argon'                                                       , ''                   ,  0),
('Gas'         , '75/25'                                                       , ''                   ,  0),
('Gas'         , '90/10'                                                       , ''                   ,  0),
('Gas'         , 'Acetylene'                                                   , ''                   ,  0),
('Gas'         , 'Propane'                                                     , ''                   ,  0),
('Gas'         , 'Oxygen'                                                      , ''                   ,  0),
('Gas'         , 'Propane Forklift'                                            , ''                   ,  0),
('Gas'         , 'Compressed Air'                                              , ''                   ,  0);